FROM openjdk:8-jre

LABEL maintainer="Martijn Dekkers <mdekkers@d2iq.com>"
LABEL copyright="Copyright (c) 2019 D2iQ, Inc."
LABEL Vendor="D2iQ, Inc."
LABEL version="1.0"
LABEL site="https://www.d2iq.com"

RUN apt-get update \
    && apt-get install -y jq xmlstarlet procps python3 python3-pip nano mc upx-ucl musl binutils patchelf wget unzip
